title: tfx-menu documentation
description: Documentation for the tfx-menu project using Just the Docs theme!
theme: just-the-docs

url: https://mcgheej.github.io/tfx-menu-docs

aux_links:
  Template Repository: https://github.com/mcgheej/tfx-menu-docs
